#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate wwwlocale.h from WebUI locale JSON files in src/locale/www/

Usage:
    py src/locale/make_wwwlocale.py              # generate wwwlocale.h
    py src/locale/make_wwwlocale.py --verify     # validate all files
"""

import json, os, glob, sys, io, gzip

if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WWW_DIR = os.path.join(SCRIPT_DIR, 'www')
OUTPUT_H = os.path.join(SCRIPT_DIR, 'wwwlocale.h')


def validate():
    errors = []
    for f in sorted(glob.glob(os.path.join(WWW_DIR, '*.json'))):
        code = os.path.basename(f).replace('.json', '')
        try:
            data = json.load(open(f, 'r', encoding='utf-8'))
        except json.JSONDecodeError as e:
            errors.append(f"{code}: invalid JSON — {e}")
            continue
        if data.get('locale_code') != code:
            errors.append(f"{code}: locale_code mismatch: {data.get('locale_code')}")
        if 'locale' not in data or 'locale_en' not in data:
            errors.append(f"{code}: missing locale/locale_en metadata")
    return errors


def bytes_to_hex_array(data, indent=2):
    """Convert bytes to C hex array string."""
    hex_str = ', '.join(f'0x{b:02X}' for b in data)
    prefix = ' ' * indent
    # Wrap at ~80 chars
    lines = []
    current = prefix
    for i, h in enumerate(hex_str.split(', ')):
        chunk = h + (',' if i < len(data) - 1 else '')
        if len(current) + len(chunk) + 1 > 100:
            lines.append(current.rstrip())
            current = prefix + chunk
        else:
            if current == prefix:
                current += chunk
            else:
                current += ' ' + chunk
    if current.strip():
        lines.append(current.rstrip())
    return '\n'.join(lines)


def generate():
    locales = {}
    for f in sorted(glob.glob(os.path.join(WWW_DIR, '*.json'))):
        code = os.path.basename(f).replace('.json', '')
        raw = open(f, 'r', encoding='utf-8').read()
        data = json.loads(raw)
        # Gzip compress
        compressed = gzip.compress(raw.encode('utf-8'), compresslevel=9)
        locales[code] = (data, compressed)

    locale_codes = sorted(locales.keys())
    n = len(locale_codes)

    lines = []
    lines.append('// AUTO-GENERATED by make_wwwlocale.py — DO NOT EDIT')
    lines.append(f'// {n} WebUI locales (gzip-compressed)')
    lines.append('#pragma once')
    lines.append('#include <pgmspace.h>')
    lines.append('')

    # Per-locale gzip-compressed PROGMEM byte arrays
    for code in locale_codes:
        _, compressed = locales[code]
        var_name = f'www_{code}'
        lines.append(f'// {code} — {len(compressed)} bytes gzipped')
        lines.append(f'const uint8_t {var_name}[] PROGMEM = {{')
        lines.append(bytes_to_hex_array(compressed))
        lines.append('};')
        lines.append('')

    # Lookup table with sizes
    lines.append(f'#define WWW_LOCALE_COUNT {n}')
    lines.append('')
    lines.append('struct WWWLocale { const char* code; const uint8_t* data; uint16_t size; };')
    lines.append('')
    lines.append(f'const WWWLocale www_locales[{n}] PROGMEM = {{')
    for code in locale_codes:
        _, compressed = locales[code]
        var_name = f'www_{code}'
        lines.append(f'  {{ "{code}", {var_name}, {len(compressed)} }},')
    lines.append('};')
    lines.append('')

    # Index JSON — flat object format (uncompressed, small enough)
    index_obj = {}
    for code in locale_codes:
        data, _ = locales[code]
        index_obj[code] = data.get('locale', code)
    index_json = json.dumps(index_obj, indent=2, ensure_ascii=False)

    lines.append(f'const char wwwlocale_index[] PROGMEM = R"WWWJSONEND(')
    lines.append(index_json)
    lines.append(f')WWWJSONEND";')
    lines.append('')

    return '\n'.join(lines)


def main():
    if '--verify' in sys.argv:
        errors = validate()
        if errors:
            print("VALIDATION ERRORS:")
            for e in errors:
                print(f"  {e}")
            sys.exit(1)
        files = len(list(glob.glob(os.path.join(WWW_DIR, '*.json'))))
        print(f"All {files} WebUI locale files pass validation.")
        return

    header = generate()
    with open(OUTPUT_H, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)
    locales_count = len(list(glob.glob(os.path.join(WWW_DIR, '*.json'))))
    print(f"Generated: {OUTPUT_H} ({locales_count} locales, gzip-compressed)")


if __name__ == '__main__':
    main()
