#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate wwwlocale.h from WebUI locale JSON files in src/locale/www/

Usage:
    py src/locale/make_wwwlocale.py              # generate wwwlocale.h
    py src/locale/make_wwwlocale.py --verify     # validate all files
"""

import json, os, glob, sys, io

if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
WWW_DIR = os.path.join(SCRIPT_DIR, 'www')
OUTPUT_H = os.path.join(SCRIPT_DIR, 'wwwlocale.h')

UNIQUE_DELIM = "WWWJSONEND"


def validate():
    errors = []
    for f in sorted(glob.glob(os.path.join(WWW_DIR, '*.json'))):
        code = os.path.basename(f).replace('.json', '')
        try:
            data = json.load(open(f, 'r', encoding='utf-8'))
        except json.JSONDecodeError as e:
            errors.append(f"{code}: invalid JSON — {e}")
            continue
        if data.get('locale_code') != code:
            errors.append(f"{code}: locale_code mismatch: {data.get('locale_code')}")
        if 'locale' not in data or 'locale_en' not in data:
            errors.append(f"{code}: missing locale/locale_en metadata")
    return errors


def generate():
    locales = {}
    for f in sorted(glob.glob(os.path.join(WWW_DIR, '*.json'))):
        code = os.path.basename(f).replace('.json', '')
        raw = open(f, 'r', encoding='utf-8').read()
        # Validate JSON
        data = json.loads(raw)
        locales[code] = (data, raw)

    locale_codes = sorted(locales.keys())
    n = len(locale_codes)

    lines = []
    lines.append('// AUTO-GENERATED by make_wwwlocale.py — DO NOT EDIT')
    lines.append(f'// {n} WebUI locales')
    lines.append('#pragma once')
    lines.append('#include <pgmspace.h>')
    lines.append('')

    # Per-locale PROGMEM raw strings
    for code in locale_codes:
        _, raw = locales[code]
        # Ensure raw doesn't contain the delimiter
        minified = raw.strip()
        var_name = f'www_{code}'
        lines.append(f'const char {var_name}[] PROGMEM = R"{UNIQUE_DELIM}(')
        lines.append(minified)
        lines.append(f'){UNIQUE_DELIM}";')
        lines.append('')

    # Lookup table
    lines.append(f'#define WWW_LOCALE_COUNT {n}')
    lines.append('')
    lines.append('struct WWWLocale { const char* code; const char* data; };')
    lines.append('')
    lines.append(f'const WWWLocale www_locales[{n}] PROGMEM = {{')
    for code in locale_codes:
        var_name = f'www_{code}'
        lines.append(f'  {{ "{code}", {var_name} }},')
    lines.append('};')
    lines.append('')

    # Index JSON — flat object format: {"en_US": "English", ...}
    index_obj = {}
    for code in locale_codes:
        data, _ = locales[code]
        index_obj[code] = data.get('locale', code)
    index_json = json.dumps(index_obj, indent=2, ensure_ascii=False)

    lines.append(f'const char wwwlocale_index[] PROGMEM = R"{UNIQUE_DELIM}(')
    lines.append(index_json)
    lines.append(f'){UNIQUE_DELIM}";')
    lines.append('')

    return '\n'.join(lines)


def main():
    if '--verify' in sys.argv:
        errors = validate()
        if errors:
            print("VALIDATION ERRORS:")
            for e in errors:
                print(f"  {e}")
            sys.exit(1)
        files = len(list(glob.glob(os.path.join(WWW_DIR, '*.json'))))
        print(f"All {files} WebUI locale files pass validation.")
        return

    header = generate()
    with open(OUTPUT_H, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)
    locales_count = len(list(glob.glob(os.path.join(WWW_DIR, '*.json'))))
    print(f"Generated: {OUTPUT_H} ({locales_count} locales)")


if __name__ == '__main__':
    main()
