#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate dsplocale.h from JSON locale files in src/locale/display/

Usage:
    py src/locale/make_dsplocale.py              # generate dsplocale.h + dsplocale.json
    py src/locale/make_dsplocale.py --verify     # validate all files, no output
    py src/locale/make_dsplocale.py --verify en_US  # validate one file
"""

import json, os, glob, sys, io

if sys.platform == 'win32':
    sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8', errors='replace')

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_DIR = os.path.dirname(SCRIPT_DIR)  # src/
ROOT_DIR = os.path.dirname(PROJECT_DIR)     # project root

DISPLAY_DIR = os.path.join(SCRIPT_DIR, 'display')
OUTPUT_H = os.path.join(SCRIPT_DIR, 'dsplocale.h')
OUTPUT_JSON = os.path.join(ROOT_DIR, 'data', 'www', 'dsplocale.json')

META_KEYS = {'locale_code', 'locale', 'locale_en'}


def load_json(path):
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)


def get_translation_keys(data):
    """Return sorted list of translation keys (excludes meta keys)."""
    return sorted(k for k in data if k not in META_KEYS)


def validate_locales():
    """Validate all locale JSON files. Returns (locales_dict, keys_list, errors)."""
    master_path = os.path.join(DISPLAY_DIR, 'en_US.json')
    if not os.path.exists(master_path):
        raise FileNotFoundError(f"Master locale not found: {master_path}")

    master = load_json(master_path)
    master_keys = get_translation_keys(master)
    errors = []
    locales = {}

    for f in sorted(glob.glob(os.path.join(DISPLAY_DIR, '*.json'))):
        code = os.path.basename(f).replace('.json', '')
        try:
            data = load_json(f)
        except json.JSONDecodeError as e:
            errors.append(f"{code}: invalid JSON — {e}")
            continue

        # Validate locale_code matches filename
        if data.get('locale_code') != code:
            errors.append(f"{code}: locale_code '{data.get('locale_code')}' != filename '{code}'")

        # Validate all required keys present
        file_keys = get_translation_keys(data)
        missing = set(master_keys) - set(file_keys)
        extra = set(file_keys) - set(master_keys)
        if missing:
            errors.append(f"{code}: missing keys: {', '.join(sorted(missing))}")
        if extra:
            errors.append(f"{code}: extra keys: {', '.join(sorted(extra))}")

        # Validate required meta
        for mk in META_KEYS:
            if mk not in data:
                errors.append(f"{code}: missing meta key '{mk}'")

        locales[code] = data

    if errors:
        return None, None, errors
    return locales, master_keys, []


def generate_header(locales, keys):
    """Generate dsplocale.h content."""
    locale_codes = sorted(locales.keys())
    n_locales = len(locale_codes)
    n_keys = len(keys)

    lines = []
    lines.append('// AUTO-GENERATED by make_dsplocale.py — DO NOT EDIT')
    lines.append(f'// {n_locales} locales, {n_keys} keys')
    lines.append('#pragma once')
    lines.append('')
    lines.append('// Validate DSP_LOCALE at compile time (set in myoptions.h)')
    lines.append('#ifndef DSP_LOCALE')
    lines.append('  #define DSP_LOCALE "en_US"')
    lines.append('#endif')
    lines.append('static_assert(')
    for i, code in enumerate(locale_codes):
        op = '||' if i < n_locales - 1 else ''
        lines.append(f'  __builtin_strcmp(DSP_LOCALE, "{code}") == 0 {op}')
    lines.append('  , "DSP_LOCALE is not a valid locale code. See locale/display/dsplocale.h for valid codes (like en_US)."')
    lines.append(');')
    lines.append('')
    lines.append('#include <pgmspace.h>')
    lines.append('')
    lines.append(f'#define L10N_LOCALE_COUNT {n_locales}')
    lines.append(f'#define L10N_KEY_COUNT {n_keys}')
    lines.append('')

    # ── Key enum ──
    lines.append('enum L10nKey : uint8_t {')
    for i, key in enumerate(keys):
        enum_name = 'L10N_' + key.upper()
        comma = ',' if i < n_keys - 1 else ''
        lines.append(f'  {enum_name}{comma}')
    lines.append('};')
    lines.append('')

    # ── Locale codes array ──
    lines.append(f'const char l10n_locale_codes[{n_locales}][6] PROGMEM = {{')
    for i, code in enumerate(locale_codes):
        comma = ',' if i < n_locales - 1 else ''
        lines.append(f'  "{code}"{comma}')
    lines.append('};')
    lines.append('')

    # ── Locale names ──
    lines.append(f'const char* const l10n_names[{n_locales}] PROGMEM = {{')
    for i, code in enumerate(locale_codes):
        comma = ',' if i < n_locales - 1 else ''
        name = locales[code].get('locale', code).replace('"', '\\"')
        lines.append(f'  "{name}"{comma}  // {code}')
    lines.append('};')
    lines.append('')

    lines.append(f'const char* const l10n_names_en[{n_locales}] PROGMEM = {{')
    for i, code in enumerate(locale_codes):
        comma = ',' if i < n_locales - 1 else ''
        name = locales[code].get('locale_en', code).replace('"', '\\"')
        lines.append(f'  "{name}"{comma}  // {code}')
    lines.append('};')
    lines.append('')

    # ── Per-string PROGMEM constants ──
    string_vars = {}  # (code, key) -> variable name
    for code in locale_codes:
        data = locales[code]
        for key in keys:
            var_name = f'l10n_{code}_{key}'
            var_name = var_name.replace('.', '_')
            string_vars[(code, key)] = var_name
            val = data.get(key, '')
            escaped = val.replace('\\', '\\\\').replace('"', '\\"')
            lines.append(f'const char {var_name}[] PROGMEM = "{escaped}";')
    lines.append('')

    # ── String pointer table ──
    lines.append(f'const char* const l10n_strings[{n_locales}][{n_keys}] PROGMEM = {{')
    for li, code in enumerate(locale_codes):
        lines.append(f'  {{ // {code}')
        for ki, key in enumerate(keys):
            var = string_vars[(code, key)]
            comma = ',' if ki < n_keys - 1 else ''
            lines.append(f'    {var}{comma}')
        inner_comma = ',' if li < n_locales - 1 else ''
        lines.append(f'  }}{inner_comma}')
    lines.append('};')
    lines.append('')

    # ── Runtime functions ──
    lines.append('// Active locale index — set at boot from config.store.displaylocale')
    lines.append('extern uint8_t _activeLocale;')
    lines.append('')
    lines.append('// Find locale index by code. Returns 0 (en_US) if not found.')
    lines.append('inline uint8_t l10n_findLocale(const char* code) {')
    lines.append(f'  for (uint8_t i = 0; i < {n_locales}; i++) {{')
    lines.append('    if (strcmp_P(code, l10n_locale_codes[i]) == 0) return i;')
    lines.append('  }')
    lines.append('  return 0; // fallback to en_US')
    lines.append('}')
    lines.append('')
    lines.append('// Get a locale string by locale index and key (PROGMEM-safe).')
    lines.append('inline const char* l10n_str(uint8_t localeIdx, L10nKey key) {')
    lines.append(f'  if (localeIdx >= {n_locales}) localeIdx = 0;')
    lines.append(f'  if ((uint8_t)key >= {n_keys}) key = (L10nKey)0;')
    lines.append('  return (const char*)pgm_read_ptr(&l10n_strings[localeIdx][(uint8_t)key]);')
    lines.append('}')
    lines.append('')
    lines.append('// ── Convenience helpers (use g_activeLocale) ──')
    lines.append('')
    lines.append('inline const char* l10n(L10nKey key) {')
    lines.append('    return l10n_str(_activeLocale, key);')
    lines.append('}')
    lines.append('')
    lines.append('inline const char* l10n_wind(uint8_t idx) {')
    lines.append('    static const L10nKey wind_keys[16] PROGMEM = {')
    lines.append('        L10N_MSG_WIND_N, L10N_MSG_WIND_NNE, L10N_MSG_WIND_NE, L10N_MSG_WIND_ENE,')
    lines.append('        L10N_MSG_WIND_E, L10N_MSG_WIND_ESE, L10N_MSG_WIND_SE, L10N_MSG_WIND_SSE,')
    lines.append('        L10N_MSG_WIND_S, L10N_MSG_WIND_SSW, L10N_MSG_WIND_SW, L10N_MSG_WIND_WSW,')
    lines.append('        L10N_MSG_WIND_W, L10N_MSG_WIND_WNW, L10N_MSG_WIND_NW, L10N_MSG_WIND_NNW')
    lines.append('    };')
    lines.append('    return l10n((L10nKey)pgm_read_byte(&wind_keys[idx % 16]));')
    lines.append('}')
    lines.append('')
    lines.append('inline const char* l10n_dow(uint8_t idx) {')
    lines.append('    static const L10nKey dow_keys[7] PROGMEM = {')
    lines.append('        L10N_DAY_SUN, L10N_DAY_MON, L10N_DAY_TUE, L10N_DAY_WED,')
    lines.append('        L10N_DAY_THU, L10N_DAY_FRI, L10N_DAY_SAT')
    lines.append('    };')
    lines.append('    return l10n((L10nKey)pgm_read_byte(&dow_keys[idx % 7]));')
    lines.append('}')
    lines.append('')
    lines.append('inline const char* l10n_month(uint8_t idx) {')
    lines.append('    static const L10nKey month_keys[12] PROGMEM = {')
    lines.append('        L10N_MON_JAN, L10N_MON_FEB, L10N_MON_MAR, L10N_MON_APR,')
    lines.append('        L10N_MON_MAY, L10N_MON_JUN, L10N_MON_JUL, L10N_MON_AUG,')
    lines.append('        L10N_MON_SEP, L10N_MON_OCT, L10N_MON_NOV, L10N_MON_DEC')
    lines.append('    };')
    lines.append('    return l10n((L10nKey)pgm_read_byte(&month_keys[idx % 12]));')
    lines.append('}')
    lines.append('')

    return '\n'.join(lines)


def generate_index_json(locales):
    """Generate dsplocale.json for WebUI."""
    entries = []
    for code in sorted(locales.keys()):
        data = locales[code]
        entries.append({
            'code': code,
            'name': data.get('locale', code),
            'name_en': data.get('locale_en', code),
        })
    return json.dumps(entries, indent=2, ensure_ascii=False) + '\n'


def main():
    mode = 'generate'
    single_verify = None

    args = [a for a in sys.argv[1:] if not a.startswith('--apply')]
    if '--verify' in sys.argv:
        mode = 'verify'
        # Check if a specific code follows
        try:
            idx = sys.argv.index('--verify')
            if idx + 1 < len(sys.argv) and not sys.argv[idx + 1].startswith('--'):
                single_verify = sys.argv[idx + 1]
        except (ValueError, IndexError):
            pass

    if single_verify:
        # Verify a single file
        path = os.path.join(DISPLAY_DIR, f'{single_verify}.json')
        if not os.path.exists(path):
            print(f"ERROR: {path} not found")
            sys.exit(1)
        master_path = os.path.join(DISPLAY_DIR, 'en_US.json')
        master = load_json(master_path)
        master_keys = get_translation_keys(master)
        data = load_json(path)
        file_keys = get_translation_keys(data)
        missing = set(master_keys) - set(file_keys)
        extra = set(file_keys) - set(master_keys)
        if missing:
            print(f"WARNING: {single_verify} missing keys: {', '.join(sorted(missing))}")
        if extra:
            print(f"WARNING: {single_verify} extra keys: {', '.join(sorted(extra))}")
        if data.get('locale_code') != single_verify:
            print(f"WARNING: {single_verify} locale_code mismatch: {data.get('locale_code')}")
        if not missing and not extra:
            print(f"OK: {single_verify} — all {len(file_keys)} keys present")
        return

    # Validate all
    locales, keys, errors = validate_locales()
    if errors:
        print("VALIDATION ERRORS:")
        for e in errors:
            print(f"  {e}")
        print(f"\n{len(errors)} error(s). Fix before generating.")
        sys.exit(1)

    print(f"Validated {len(locales)} locales with {len(keys)} keys each.")

    if mode == 'verify':
        print("All files pass validation.")
        return

    # Generate header
    header = generate_header(locales, keys)
    with open(OUTPUT_H, 'w', encoding='utf-8', newline='\n') as f:
        f.write(header)
    print(f"Generated: {OUTPUT_H}")

    # Generate WebUI index
    index = generate_index_json(locales)
    with open(OUTPUT_JSON, 'w', encoding='utf-8', newline='\n') as f:
        f.write(index)
    print(f"Generated: {OUTPUT_JSON}")


if __name__ == '__main__':
    main()
